config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    get 'home/index'
    get 'posts/new', to: 'posts#new'
    post "posts" => "posts#create"
    get 'posts/:id/edit', to: 'posts#edit'
    delete 'posts/:id/destroy', to: 'posts#destroy'
    patch 'posts/:id', to: 'posts#update'
    get 'posts/:id', to: 'posts#show'
    root 'home#index'
    get 'home/index'
    root 'posts#index'
    resources :posts do
      resources :comments, only: [:create, :destroy]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :body
  end
 has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, {only: [:create, :edit, :update, :destroy, :new]}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(comment_params)
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: post_url(post.id))
    else
      flash[:danger] = "コメントできません"
      redirect_back(fallback_location: post_url(post.id))
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: post_path(post))
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @posts = Post.all
      @post = Post.new
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :post_params, only: [:create]
  before_action :set_my_thread, only: [:show,:update,:edit,:destroy]

  def new
    @post = Post.new
  end

  #新しく投稿されたテキストを受け取るアクション
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "投稿を作成しました"
      redirect_to("/home/index")
    else
      render("posts/new")
    end
  end

    #投稿内容を更新する
    def update
      @post = Post.find(params[:id])
       if @post.update(post_params)
         flash[:notice] = "投稿を編集しました"
         redirect_to("/home/index")
       else
         render 'edit'
       end
    end

    def show
      @post = Post.find(params[:id])
      @comments = @post.comments
      @comment = Comment.new
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      flash[:notice] = "投稿を削除しました"
      redirect_to("/home/index")
    end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_my_thread
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
  <div class="index">
    <h1>投稿一覧</h1>
  </div>
  <% @posts.each do |post| %>
    <div class="post-index">
      <%= link_to(post.title, "/posts/#{post.id}") %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div class="menu2">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to("新規投稿", "/posts/new") %>
      <p>メールアドレス： <%= current_user.email %></p>
    </div>
  <% else %>
    <div class="menu">
      <%= link_to "ログイン", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
    </div>
    <div class="not-login">
      <h2>現在ログインしていません</h2>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>keiziban</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/siimple@3.3.1/dist/siimple.min.css">

  </head>

  <body>
    <header>
      <div class="siimple-box siimple-box--primary">
          <div class="siimple-box-title">keiziban</div>
      </div>
    </header>
    
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集してください</h1>
<%= form_for @post,:url => {:action => :update} do |f| %>
<% @post.errors.full_messages.each do |message| %>
  <%= message %>
<% end %>
  <%= f.text_field :title %>
  <%= f.text_area :body %>
  <%= f.submit "投稿" %>
<% end %>

app/views/posts/new.html.erb
<div class="siimple-form">
  <h1>新規投稿</h1>
  <%= form_for(@post) do |f| %>
    <% @post.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
    <div class="siimple-form-detail">
      <h1>title</h1>
      <%= f.text_field :title %>
    </div>
    <div class="siimple-form-field">
        <div class="siimple-form-field-label">
          <h1>text</h1>
          <%= f.text_area :body %>
        </div>
    </div>
      <%= f.submit '投稿', :class => 'postnew' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="show">
  <h1>投稿詳細ページ</h1>
  <h2>
    <%= @post.title %>
  </h2>
  <p>
    <%= link_to("編集", "/posts/#{@post.id}/edit") %>
    <%= link_to("削除", "/posts/#{@post.id}/destroy", {method: "delete"}) %>
  </p>

  <h2>コメント一覧</h2>
  <% @comments.each do |c| %>
    <div>
      <%= c.content %>
      <hr>
      <p><%= link_to "削除", post_comment_path(@post, id: c.id), method: :delete %></p>
    </div>
  <% end %>

  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_field :content %>
    <%= f.submit 'コメントする' %>
   <% end %>
</div>